"""add analysis_jobs

Revision ID: 6c0943361e16
Revises: dda0b01608f9
Create Date: 2026-08-13 14:09:04.169467

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c0943361e16'
down_revision: str | Sequence[str] | None = 'dda0b01608f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('plugin', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('result_key', sa.String(length=256), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('sensor_feature_time_idx'), table_name='sensor_feature')
    op.drop_index(op.f('idx_sensor_raw_device_point'), table_name='sensor_raw')
    op.drop_index(op.f('sensor_raw_time_idx'), table_name='sensor_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('sensor_raw_time_idx'), 'sensor_raw', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_sensor_raw_device_point'), 'sensor_raw', ['device_id', 'point_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('sensor_feature_time_idx'), 'sensor_feature', [sa.literal_column('time DESC')], unique=False)
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
