"""v0.8b sensor channel reading refactor

Revision ID: af5a7548852c
Revises: 1e4cdedf9b41
Create Date: 2026-08-14 11:02:11.788085

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'af5a7548852c'
down_revision: str | Sequence[str] | None = '1e4cdedf9b41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('sensor_code', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('last_calibration', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('channel_code', sa.String(length=64), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('sampling_rate', sa.Integer(), server_default='1', nullable=False),
    sa.Column('position_offset', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('axis', sa.String(length=8), nullable=True),
    sa.Column('alert_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=8), server_default='good', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('time', 'channel_id')
    )
    op.drop_table('sensor_feature')
    op.drop_table('sensor_raw')
    op.add_column('alerts', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('alerts_point_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'channels', ['channel_id'], ['id'])
    op.drop_column('alerts', 'point_id')
    op.add_column('analysis_jobs', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('analysis_jobs_point_id_fkey'), 'analysis_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_jobs', 'channels', ['channel_id'], ['id'])
    op.drop_column('analysis_jobs', 'point_id')
    op.drop_column('points', 'sampling_rate')
    op.drop_column('points', 'unit')
    op.drop_column('points', 'alert_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('alert_rules', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('unit', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('points', sa.Column('sampling_rate', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('analysis_jobs', sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analysis_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_jobs_point_id_fkey'), 'analysis_jobs', 'points', ['point_id'], ['id'])
    op.drop_column('analysis_jobs', 'channel_id')
    op.add_column('alerts', sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_point_id_fkey'), 'alerts', 'points', ['point_id'], ['id'])
    op.drop_column('alerts', 'channel_id')
    op.create_table('sensor_raw',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quality', sa.VARCHAR(length=8), server_default=sa.text("'good'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time', 'device_id', 'point_id', name=op.f('sensor_raw_pkey'))
    )
    op.create_table('sensor_feature',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rms_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('peak_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('time', 'device_id', 'point_id', name=op.f('sensor_feature_pkey'))
    )
    op.drop_table('readings')
    op.drop_table('channels')
    op.drop_table('sensors')
    # ### end Alembic commands ###
