"""v0.8c 3d model upload

Revision ID: c4f21bee2f8b
Revises: af5a7548852c
Create Date: 2026-08-14 17:21:27.309007

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c4f21bee2f8b'
down_revision: str | Sequence[str] | None = 'af5a7548852c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('3d_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subitem_id', sa.Integer(), nullable=False),
    sa.Column('original_key', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('glb_key', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subitem_id'], ['subitems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_3d_models_subitem_id'), '3d_models', ['subitem_id'], unique=False)
    op.drop_column('subitems', 'model_file_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subitems', sa.Column('model_file_key', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_3d_models_subitem_id'), table_name='3d_models')
    op.drop_table('3d_models')
    # ### end Alembic commands ###
