"""v0.9 add note field to device/sensor/channel/model

Revision ID: f1f01d4a2fb2
Revises: 0c8f4e8484f3
Create Date: 2026-08-14 21:40:51.406334

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f1f01d4a2fb2'
down_revision: str | Sequence[str] | None = '0c8f4e8484f3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('3d_models', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('channels', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('devices', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('sensors', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'note')
    op.drop_column('devices', 'note')
    op.drop_column('channels', 'note')
    op.drop_column('3d_models', 'note')
    # ### end Alembic commands ###
